In [1]:
import pandas as pd

## Load the first MIDUS datafile from the 02760 set, from local directory

In [5]:
!ls -l ../omdena/Humanity/MIDUS/ICPSR_02760/

total 2232
-rw-r--r--@  1 ethanhaley  staff  389007 Feb 23 21:48 02760-Documentation-readme.pdf
-rw-r--r--@  1 ethanhaley  staff  453510 Feb 23 21:48 02760-Documentation-sampdesc.pdf
-rw-r--r--@  1 ethanhaley  staff   16585 Feb 23 21:48 02760-descriptioncitation.html
-rw-r--r--@  1 ethanhaley  staff   11946 Feb 23 21:48 02760-manifest.txt
-rw-r--r--@  1 ethanhaley  staff  252842 Feb 23 21:48 02760-related_literature.txt
drwxr-xr-x@ 14 ethanhaley  staff     448 Feb 23 21:50 DS0001
drwxr-xr-x@  8 ethanhaley  staff     256 Feb 23 21:50 DS0002
drwxr-xr-x@  5 ethanhaley  staff     160 Feb 23 21:50 DS0003
-rw-r--r--@  1 ethanhaley  staff    5908 Feb 23 21:48 TermsOfUse.html
-rw-r--r--@  1 ethanhaley  staff    1108 Feb 23 21:48 series-203-related_literature.txt

In [6]:
!ls -l ../omdena/Humanity/MIDUS/ICPSR_02760/DS0001/

total 164176
-rw-r--r--@ 1 ethanhaley  staff  18566841 Feb 23 21:48 02760-0001-Codebook-ICPSR.pdf
-rw-r--r--@ 1 ethanhaley  staff  44427704 Feb 23 21:48 02760-0001-Data.tsv
-rw-r--r--@ 1 ethanhaley  staff    534866 Feb 23 21:48 02760-0001-Documentation-age.pdf
-rw-r--r--@ 1 ethanhaley  staff   1028620 Feb 23 21:48 02760-0001-Documentation-convars.pdf
-rw-r--r--@ 1 ethanhaley  staff    329381 Feb 23 21:48 02760-0001-Documentation-occup.pdf
-rw-r--r--@ 1 ethanhaley  staff    669763 Feb 23 21:48 02760-0001-Documentation-scales.pdf
-rw-r--r--@ 1 ethanhaley  staff  12325277 Feb 23 21:48 02760-0001-Documentation-techrpt.pdf
-rw-r--r--@ 1 ethanhaley  staff    480664 Feb 23 21:48 02760-0001-Documentation-techrpt_method_MULTI.pdf
-rw-r--r--@ 1 ethanhaley  staff    440145 Feb 23 21:48 02760-0001-Documentation-weights.pdf
-rw-r--r--@ 1 ethanhaley  staff    507157 Feb 23 21:48 02760-0001-Questionnaire-phone.pdf
-rw-r--r--@ 1 ethanhaley  staff    649067 Feb 23 21:48 02760-0001-Questionnaire-saq.pdf
-rw-r--r--@ 1 ethanhaley  staff   4074242 Feb 23 21:48 02760-0001-Zipped_package-midusxml.zip

In [8]:
# so this is the second line of that list above, 44MB
df = pd.read_csv("../omdena/Humanity/MIDUS/ICPSR_02760/DS0001/02760-0001-Data.tsv", sep='\t')
df.shape

(7108, 2098)

In [9]:
df.columns[:50]

Index(['M2ID', 'M2FAMNUM', 'SAMPLMAJ', 'A1STATUS', 'A1PAGE_M2', 'A1PRAGE_2019',
       'M1AGE_FLAG', 'A1PBYEAR', 'A1PBYEAR_2019', 'M1BYEAR_FLAG', 'A1PRSEX',
       'QL2', 'QL3', 'HH_CELL', 'NPRB_SEX', 'SEX_CELL', 'NPRB_WHO', 'WHO',
       'PROB_R', 'MO', 'DAY', 'RECON', 'MO_RCVD', 'DY_RCVD', 'TOT_SIBS',
       'ZYGCAT', 'A1PI_MO', 'A1PI_YR', 'A1WGHT1', 'A1WGHT2', 'A1PWGHT1',
       'A1PWGHT2', 'A1PWGHT3', 'A1PWGHT4', 'A1PWGHT5', 'A1PWGHT6', 'A1PWGHT7',
       'A1PWGHT8', 'A1SWGHT1', 'A1SWGHT2', 'A1SWGHT3', 'A1SWGHT4', 'A1SWGHT5',
       'A1SWGHT6', 'A1SWGHT7', 'A1SWGHT8', 'A1PA4', 'A1PA5', 'A1PA6', 'A1PA7'],
      dtype='object')

## Browse the 02760-0001-Codebook-ICPSR.pdf, and pick out a few features

In [10]:
features = ['M2ID', 'M2FAMNUM', 'SAMPLMAJ', 'A1PAGE_M2', 'A1PRSEX', 'A1PI_MO', 'A1PI_YR', 'A1PA4', 'A1PA5',
            'A1PA6', 'A1PA9', 'A1PA10', 'A1PA13', 'A1PA15', 'A1PA33', 'A1PA34', 'A1PA31', 'A1PA37', 'A1PCACRS',
            'A1PA41', 'A1PA40', 'A1PA42', 'A1PA43', 'A1PA44', 'A1PA45', 'A1PA46', 'A1PA52', 'A1PA53', 'A1PA53A',
            'A1PA54', 'A1PA55', 'A1PA56', 'A1PA57', 'A1PA58', 'A1PA80', 'A1PA81', 'A1PA85A', 'A1PA85D', 'A1PB1',
            'A1PB3A', 'A1PB3B', 'A1POCC', 'A1PIND', 'A1POCMJ', 'A1PINMJ', 'A1PTSEI', 'A1PTEARN', 'A1PTEDU', 'R_FMNHR',
            'R_FMNYR', 'R_MMNHR', 'R_MMNYR', 'A1PB11', 'A1PB11A', 'A1PB17', 'A1PB19', 'A1PB27', 'A1PB28A', 'A1POCCS',
            'A1PINDS', 'A1POCSMJ', 'A1PINSMJ', 'A1PTSEIS', 'A1PB35', 'A1PB37', 'A1PD1', 'A1PD2', 'A1PD3', 'A1PD8',
            'A1PD9', 'A1PD9A', 'A1PD4', 'A1PD5', 'A1PD6', 'A1PD7', 'A1SA1', 'A1SA2', 'A1SA3', 'A1SA4', 'A1SA5',
            'A1SA6A', 'A1SA6B', 'A1SA6C', 'A1SA6D', 'A1SA7A', 'A1SA8E', 'A1SA9S', 'A1SA9T', 'A1SA9U', 'A1SA9V',
            'A1SA9W', 'A1SA9X', 'A1SA9Y', 'A1SA9Z', 'A1SA9AA', 'A1SA9BB', 'A1SA9CC', 'A1SCHRON', 'A1SRXMED',
            'A1SVITAM', 'A1SPOSAF', 'A1SNEGAF', 'A1SA18', 'A1SA19', 'A1SVIGOR', 'A1SA20', 'A1SA21', 'A1SMODER',
            'A1SA25', 'A1SA26', 'A1SA27', 'A1SA28', 'A1SA29', 'A1SALTER', 'A1SF1A', 'A1SF1B', 'A1SF1C', 'A1SF1D',
            'A1SF1E', 'A1SF1F', 'A1SF1G', 'A1SF1H', 'A1SF1I', 'A1SF1J', 'A1SF1K', 'A1SF1L', 'A1SF1M', 'A1SF1N',
            'A1SF1O', 'A1SF1P', 'A1SF1Q', 'A1SF1R', 'A1SF1S', 'A1SF1T', 'A1SF1U', 'A1SF1V', 'A1SF1W', 'A1SF1X',
            'A1SF1Y', 'A1SF3M', 'A1SF3N', 'A1SF3O', 'A1SF3P', 'A1SPERSI', 'A1SCHANG', 'A1SREAPP', 'A1SDIREC',
            'A1STODAY', 'A1SFORSG', 'A1SINSGH', 'A1SSUFFI', 'A1SADVIC', 'A1SF4W', 'A1SI1D1', 'A1SI1D2', 'A1SI1D3',
            'A1SI22', 'A1SI23', 'A1SI24', 'A1SGENER', 'A1SSWBSC', 'A1SHOMET', 'A1SFAMSO', 'A1SKINPO', 'A1SKINNE',
            'A1SFDSOL', 'A1SFDSPO', 'A1SFDSNE', 'A1SP1', 'A1SP2', 'A1SP3', 'A1SP4', 'A1SP5', 'A1SSPSOL', 'A1SSPEMP',
            'A1SSPCRI', 'A1SP29', 'A1SP30', 'A1SQ1', 'A1SQ2', 'A1SQ3', 'A1SQ4', 'A1SQ5', 'A1SQ6', 'A1SQ7', 'A1SQ8',
            'A1SR1', 'A1SR2A', 'A1SR2B', 'A1SR2C', 'A1SS2', 'A1SS7R', 'A1SS10']
len(features)

193

Bethel and Will -- I chose these features based on a pretty loose logic:  We need the basic ID stuff of course, like the first few features, and then the demographic/physical stuff, like age/height/weight/gender.  But it's pretty much a free-for-all after that.  I relied a lot on the criteria they used for that DNN model feature selection in the article I linked to in our DM.  Specifically, the features that leak info about how old the app user is won't help us much.  So e.g. categories like "how old are your children" kind of gives away the user's age.  Or "how long have you lived at current address", or a ton of other info, is just very correlated with user age.  So why does that even matter?  I'm not sure :) , because our ML experts in this project haven't clearly specified their target variables, which is a debate I can't wait to hear, but at any rate, our features should be useful in determining how much someone's BA/RoA/BAA, whatever you call it, is changing, based on their actions.  So I'm kind of avoiding things that reveal the person's actual age ("CA"), other than including their age here so that we can check back on them later in the MIDUS study and see "Oh, look, they've aged 8 years on the calendar, but their survey responses are more like 10 years of BA".  

But even claiming I used any logic here, I was not consistent in some of the columns I included/omitted.  For example, a lot of broad categories have annoyingly many questions to ask the same thing ("Do you feel like you are in control of your life?", "Do you feel like someone else is controlling your life", "If you set your mind to something can you accomplish it", "Has everything already been determined already", etc, etc).  So in some cases, I included all 10 annoying questions, but you'll find that there's usually a sort of summary number that MIDUS used to quantify it all in one number, at the end of the section.  So I included a mix of those types here, and maybe you guys can weigh in on what you think.

### my next moves, pretty much in order of priority

1) listen to you guys' thoughts about features

2) see how these features repeat in the other 23 datasets, especially ones where we get to see the same person's data  

3) cross fingers that Japan data is similar    

4) specify the ranges of the variables and their meaning  

5) combine all 23 sets, as much as possible

6) bring it to a google sheet before saturday, so we can let people know the value of this kind of data

### so here's the meaning of all those features

In [11]:
# map the column names to something interpretable

meaning = ['unique 5-digit person ID', 'unique 6-digit family ID', 'which study this person is from',
           'age at time of phone interview', 'gender', 'interview month', 'interview year', 
           'self-evaluate physical health', 'self-evaluate mental/emotional health', 
           'self-evaluate own health vs. others of same age and gender', 
           'how was your physical health at 16 years old', 'how was mental health at 16 years old', 
           'how is your risk of heart attack vs same age and gender', 'how much do you worry about your heart', 
           'taking prescription meds for high b.p.', 'doing anything other than rx meds for high b.p.',
           'last b.p. reading', 'how does your cancer risk compare to others of your age and gender',
           'self-evaluate your cancer risk', 'age first cigarette', 'ever smoked regularly', 
           'age first smoked regularly', 'now smoking regularly', 
           'cigs/day during heaviest year of smoking, if currently smoking', 'ever tried to quit smoking',
           'age last smoked regularly', 
           'age first drink alcohol', 'ever had a period of at least one drink on at least 3 days a week',
           'age began drinking 1+/wk for 3+ days/wk', 'during heaviest drinking year, how frequently had 1+ drink',
           'when you drank most, how many did you drink', 'age when you last drank often', 
           'felt sad/depressed for 2+ wks/yr', 'how much of the day did the sadness last',
           'how much you worry compared to others like you', 'frequency of worrying', 
           'how often restless from worries',"how often can't sleep from worries",
           'highest level of education completed', 'currently working', 'self-employed', 'occupation category',
           'industry of your occupation', 'major category of your occupation', 'major category of your industry', 
           'socio-economic index', 'logit all earn >= 14.30', 'logit all education some college',
           'females hourly earning', 'females annual earning', 'males hourly earning', 'males annual earning',
           'hours/week for pay at main job', 'hours/week for pay at second job', 'marital status', 
           'number of marriages', 'highest education for spouse/partner', 'spouse/partner currently working',
           'spouse/partner occupation', 'spouse/partner industry', 'spouse/partner major grouping of occupation',
           'spouse/partner major grouping of industry', 'spouse socio-economic index',
           'number of biological children', 'number of non-biological children', 'satisfaction with life now',
           'control over life', 'satisfaction with self',
           'rate your contribution to the welfare and well-being of others',
           'disappointed with life achievements so far', 'how strong is assessment of life disappointment',
           'how outgoing/sociable/interested in others are you', 'are you a worrier', 'are you a curious person', 
           'are you optimistic', 'rate your current health', 'rate health 10 years ago', 
           'estimate health 10 years from now', 'rate your control over your health',
           'how much thought/effort do you put into your health', 'your energy now vs. 5 years ago', 
           'your fitness now vs. 5 yrs ago', 'your physique now vs. 5 yrs ago', 'your weight now vs. 5 yrs ago',
           'keeping healthy depends on what you do', 'you have low pain tolerance', 
           'high b.p. or hypertension in last year', 'anxiety/depresion in last year',
           'alcohol/drug problem in last year', 'migraines in last year', 'chronic sleep problems in last year', 
           'diabetes/high blood sugar in last year', 'neurological disorder in last year', 'stroke in last year',
           'ulcer in last year', 'hernia in last year', 'piles/hemarrhoids in last year', 
           'number of chronic conditions in past year', 'number of prescription meds in last year',
           'taking vitamins/supplements regularly', "summary of how cheerful you've been recently",
           "summary of how horrible you've felt recently",
           'summer vigorous activity, how often you run or lift weights long enough to sweat',
           'winter vigorous activity, how often you run or lift weights long enough to sweat',
           'times per month vigorous activity', 'summer moderate activity', 'winter moderate activity', 
           'times per month moderate activity', 'height in inches', 'perception of own weight', 'weight in pounds',
           'weight a year ago', 'weight when 21 years old', 'have used alternative medical treatments past year',
           'I like most aspects of my personality','I am pleased with how life has turned out',
           'some people wander aimlessly, but not I', 'everyday demands often get me down', 
           'disappointed with achievements in life', 'difficult to maintain close relationships', 
           "I live life one day at a time and don't really worry about the future", 
           "I'm in charge of my life situation", "I'm good at managing daily responsibilities orf life",
           "I've done all there is to do in life", 'life has been a continuous process of learning/changing/growing',
           'important to have new experiences that challenge how I see myself and the world',
           'others describe me as giving/willing to share my time', 'gave up trying to improve long ago',
           'I tend to be influenced by others with strong opinions', 
           'I have not experienced many warm/trusting relationships',
           "I trust my own opinions even if they're different", 
           'I judge myself by my own values of what is important',
           'Not much can I do to change the important things in life',
           'I often feel helpless dealing with life problems',
           'I can do most anything I set my mind to', 'Mostly what I can do is determined by others',
           'What happens in life is beyond my control', 'When I really want something I find a way to get/do it',
           'Many things interfere with what I want to do', 'I find positives even in the worst situations',
           'I find positives even in the worst situations',
           'I like to plan for the future', 'I know what I want in life', 'persistent in goal striving',
           'lower aspirations', 'positive reappraisal', 'self-directedness and planning', 'live for today', 
           'foresight and anticipation', 'insight into past', 'self-sufficiency', 'advice-seeking', 'I am active', 
           'volunteering hours/week 10 years ago', 'volunteering hours/week now', 
           'volunteering hours/week 10 years from now', 'job effect on physical health', 
           'job effect on mental/emotional health', 'accident/injury risk at work',
           'summary of your home/work interaction stress',
           'summary of your social contribution/well-being', 'summary of your perceived quality of my neighborhood', 
           'summary of your family affectual solidarity', 'summary of the support you get from family',
           'summary of strain from family', 'summary of friends affectual solidarity', 'summary of support from friends',
           'summary of strain from friends', 'rate current marriage/relationship', 'rate marriage/relationship 10 yrs ago', 
           'rate marriage/relationship 10 years from now', 'control over marriage/relationship',
           'how much thought/effort you put into marriage/relationship these days', 'spouse/partner affectual solidarity',
           'support from spouse/partner', 'strain from spouse/partner', 'describe current physical health of spouse/partner',
           'describe mental health of current spouse/partner', 'rate sexual aspect of current life',
           'rate sexual aspect of life 10 yrs ago', 'predict sexual aspect of life 10 years from now',
           'control of sexual aspect of life', 'how much thought/effort you put into sexual aspect of life',
           'number of sexual partners in last year', 'sexual preference', 'sexual frequency last 6 months',
           'religion', 'how religious are you', 'how spiritual are you', 'how superstitious are you',
           'you are american but which ethnic group/country best describes you', 'race',
           'how important is it to marry someone in your same race']

In [13]:
keymap = pd.DataFrame({"name":features, "meaning":meaning})
keymap.head(11)

         name                                            meaning
0        M2ID                           unique 5-digit person ID
1    M2FAMNUM                           unique 6-digit family ID
2    SAMPLMAJ                    which study this person is from
3   A1PAGE_M2                     age at time of phone interview
4     A1PRSEX                                             gender
5     A1PI_MO                                    interview month
6     A1PI_YR                                     interview year
7       A1PA4                      self-evaluate physical health
8       A1PA5              self-evaluate mental/emotional health
9       A1PA6  self-evaluate own health vs. others of same ag...
10      A1PA9       how was your physical health at 16 years old

In [14]:
df = df[features]
df.head(11)

,M2ID,M2FAMNUM,SAMPLMAJ,A1PAGE_M2,A1PRSEX,A1PI_MO,A1PI_YR,A1PA4,A1PA5,A1PA6,...,A1SQ6,A1SQ7,A1SQ8,A1SR1,A1SR2A,A1SR2B,A1SR2C,A1SS2,A1SS7R,A1SS10
0,10001,110498,2,53,1,8,1996,3,4,2,...,2,1,1,39,3,4,4,47,1,2
1,10002,100001,1,60,1,3,1995,5,5,2,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
2,10004,100002,1,69,1,8,1995,2,5,2,...,2,1,3,2,3,2,4,38,1,4
3,10005,120803,3,70,2,4,1995,3,3,1,...,1,1,6,32,4,2,4,3,1,4
4,10006,120772,3,51,2,7,1995,3,3,2,...,1,2,6,33,3,2,4,36,1,2
5,10007,120004,3,35,2,3,1995,3,3,4,...,1,1,6,5,1,1,3,98,1,1
6,10008,120206,3,63,1,3,1995,4,5,3,...,2,1,3,33,2,2,4,33,1,1
7,10009,100003,1,25,2,7,1995,4,3,3,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
8,10010,120378,3,46,1,4,1995,3,3,2,...,2,1,4,5,2,2,4,98,1,1
9,10011,110475,2,44,2,7,1996,5,5,3,...,2,1,6,33,2,1,4,36,6,3
10,10013,100004,1,27,1,3,1995,3,4,2,...,98,8,8,98,8,8,8,98,8,8